import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const exportPDF = (summary, transactions) => {
  const doc = new jsPDF();

  // Title
  doc.setFontSize(22);
  doc.text("Personal Finance Report", 105, 20, { align: "center" });

  // Date
  doc.setFontSize(11);
  doc.text(
    `Generated on: ${new Date().toLocaleDateString()}`,
    14,
    35
  );

  // Line
  doc.line(14, 40, 196, 40);

  // Summary
  doc.setFontSize(16);
  doc.text("Summary", 14, 50);

  doc.setFontSize(12);

  doc.text(
    `Income : INR ${Number(summary.income).toLocaleString()}`,
    14,
    60
  );

  doc.text(
    `Expense : INR ${Number(summary.expense).toLocaleString()}`,
    14,
    68
  );

  doc.text(
    `Balance : INR ${Number(summary.balance).toLocaleString()}`,
    14,
    76
  );

  // Transactions Table
  autoTable(doc, {
    startY: 90,

    head: [["Date", "Category", "Type", "Description", "Amount"]],

    body: transactions.map((t) => [
      new Date(t.date).toLocaleDateString(),
      t.category,
      t.type,
      t.description,
      `INR ${Number(t.amount).toLocaleString()}`,
    ]),
  });

  // Footer
  doc.setFontSize(10);

  doc.text(
    "Generated by Personal Finance Tracker",
    105,
    doc.internal.pageSize.height - 10,
    { align: "center" }
  );

  const today = new Date().toISOString().split("T")[0];
  doc.save(`Finance_Report_${today}.pdf`);
};

export default exportPDF;